#Default port is 8761
server:
  port: 8761

eureka:
  client:
    # 유레카 서비스에 (자신을) 등록하지 않는다.
    registerWithEureka: false
    # 레지스트리 정보를 로컬에 캐싱하지 않는다.
    fetchRegistry: false
  server:
    # 서버가 요청을 받기 전 대기할 초기 시간 (로컬에서만 사용)
    waitTimeInMsWhenSyncEmpty: 5
    peer-node-read-timeout-ms: 10000
  serviceUrl:
    defaultZone: http://localhost:8761

