# actuator endpoints (health, env, refresh and others) for testing
# 테스트를 위한 노출이므로 운영에는 노출되면 안될듯
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    # 서비스 이름 대신 서비스 IP 주소 등록
    preferIpAddress: true
  client:
    # 유레카에 서비스 등록
    registerWithEureka: true
    # 유레카 서비스 위치
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

