server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        # encrypt.enabled should moved to bootstrap.yml
        # encrypt.enabled: false
        git:
          uri: https://github.com/hmg0616/msainaction-config-repo/
          searchPaths: licensingservice,organizationservice
          #username: native-cloud-apps
          #password: 0ffended